### ISSUE TITLE
consider the need for console logs

### ISSUE THREAD

**Issue by aric87** [yolixtly/flicker-search#7]
Here, you can probably remove: https://github.com/yolixtly/flicker-search/blob/master/app/app.js#L60
Here, it should stay: https://github.com/yolixtly/flicker-search/blob/master/app/app.js#L68 and you should throw a message to the user to get it and send to you (not realistic for a project like this, but in a production app you might. )

**Comment by yolixtly** [comment]
Hi Aric, when you say 'you should throw a message to the user to get it and send to you'  you mean to add an alert message for example? I have set a variable vm.errorRequest = true, so that in case an error occurs, the user is notified. 

Is that your suggestion? If not can you explain a little more :) thank you

**Comment by aric87** [comment]
Yea, so if you tell the user there's an error, you can direct them to grab the console log and email it to you, so you know what the error was. If you want. You can also leave it as just letting them know there is an error.
